export const LOCATION_RADIUS = 7;
export const JUMP_MARGIN = 10;
export const JUMPS_CONTROL_POINT_DISTANCE = 30;
export const JUMP_HOVER_ZONE_WIDTH = 10;
export const JUMPS_LOOP_CONTROL_POINT_DISTANCE = 40;
export const JUMP_END_LOCATION_RADIUS = 12;
export const JUMP_ARROW_LENGTH = 8;

export const LOCATION_DROP_RADIUS = LOCATION_RADIUS + JUMP_MARGIN;

export const CANVAS_PADDING = 150;
