export const LOCATION_RADIUS = 7;
export const JUMP_MARGIN = 10;
export const JUMPS_CONTROL_POINT_DISTANCE = 30;
export const JUMP_HOVER_ZONE_WIDTH = 10;

export const LOCATION_DROP_RADIUS = LOCATION_RADIUS + JUMP_MARGIN;
